# Generated by Django 5.1.1 on 2024-12-03 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('category_id', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('images', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status_id', models.SmallIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('category_id', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_id', models.SmallIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_adverts', to='unique_ad_image_generator.advert')),
            ],
        ),
    ]
