# Generated by Django 5.1.1 on 2024-12-17 23:56

import unique_ad_image_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_ad_image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='backet_name',
            field=models.CharField(default='adverts-bucket', max_length=256),
        ),
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='adverts/zips/', validators=[unique_ad_image_generator.models.validate_zip_file]),
        ),
    ]
